const getContent = require('../../../../app/batching/get-content')
let batch

describe('get content', () => {
  beforeEach(async () => {
    batch = {
      scheme: {
        batchProperties: {
          source: 'SitiELM'
        }
      },
      paymentRequests: [{
        frn: 1234567890,
        marketingYear: 2022,
        deliveryBody: 'RP00',
        currency: 'GBP',
        invoiceNumber: 'SFI12345678',
        agreementNumber: 'SFI12345678',
        contractNumber: 'SIP123456',
        dueDate: '2021-08-02',
        schedule: 'M12',
        invoiceLines: [{
          fundCode: 'DRD10',
          schemeCode: '80001',
          accountCode: 'SOS273',
          description: 'G00 - Gross value of payment',
          value: 10021
        }, {
          fundCode: 'DRD10',
          schemeCode: '80001',
          accountCode: 'SOS273',
          description: 'P02 - Over declaration penalty',
          value: -2005
        }, {
          fundCode: 'DRD10',
          schemeCode: '80002',
          accountCode: 'SOS274',
          description: 'G00 - Gross value of payment',
          value: 10000
        }, {
          fundCode: 'DRD10',
          schemeCode: '80003',
          accountCode: 'SOS277',
          description: 'G00 - Gross value of payment',
          value: 20
        }, {
          fundCode: 'DRD10',
          schemeCode: '80003',
          accountCode: 'SOS275',
          description: 'P02 - Over declaration penalty',
          value: -10
        }]
      }]
    }
  })

  test('should return as array', async () => {
    const content = await getContent(batch)
    expect(Array.isArray(content)).toBeTruthy()
  })

  test('should include correct content', async () => {
    const content = await getContent(batch)
    expect(content).toStrictEqual([
      [
        'Vendor',
        1234567890,
        '',
        'DRD10',
        '80001',
        2022,
        'RP00',
        'SFI12345678',
        '80.16',
        'GBP',
        'legacy',
        '',
        'SIP123456',
        '',
        1,
        '',
        '',
        '',
        '',
        'BACS_GBP',
        'SitiELM',
        '',
        '',
        '',
        '02/08/2021',
        'GBP',
        '',
        '',
        'M12',
        'END'
      ],
      [
        'Ledger',
        'SOS273',
        '',
        'DRD10',
        '80001',
        2022,
        'RP00',
        'SFI12345678',
        '100.21',
        'GBP',
        'legacy',
        '',
        '',
        '',
        '',
        '',
        '',
        'G00 - Gross value of payment',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        'SFI12345678',
        '',
        'END'
      ],
      [
        'Ledger',
        'SOS273',
        '',
        'DRD10',
        '80001',
        2022,
        'RP00',
        'SFI12345678',
        '-20.05',
        'GBP',
        'legacy',
        '',
        '',
        '',
        '',
        '',
        '',
        'P02 - Over declaration penalty',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        'SFI12345678',
        '',
        'END'
      ],
      [
        'Vendor',
        1234567890,
        '',
        'DRD10',
        '80002',
        2022,
        'RP00',
        'SFI12345678',
        '100.00',
        'GBP',
        'legacy',
        '',
        'SIP123456',
        '',
        1,
        '',
        '',
        '',
        '',
        'BACS_GBP',
        'SitiELM',
        '',
        '',
        '',
        '02/08/2021',
        'GBP',
        '',
        '',
        'M12',
        'END'
      ],
      [
        'Ledger',
        'SOS274',
        '',
        'DRD10',
        '80002',
        2022,
        'RP00',
        'SFI12345678',
        '100.00',
        'GBP',
        'legacy',
        '',
        '',
        '',
        '',
        '',
        '',
        'G00 - Gross value of payment',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        'SFI12345678',
        '',
        'END'
      ], [
        'Vendor',
        1234567890,
        '',
        'DRD10',
        '80003',
        2022,
        'RP00',
        'SFI12345678',
        '0.10',
        'GBP',
        'legacy',
        '',
        'SIP123456',
        '',
        1,
        '',
        '',
        '',
        '',
        'BACS_GBP',
        'SitiELM',
        '',
        '',
        '',
        '02/08/2021',
        'GBP',
        '',
        '',
        'M12',
        'END'
      ],
      [
        'Ledger',
        'SOS277',
        '',
        'DRD10',
        '80003',
        2022,
        'RP00',
        'SFI12345678',
        '0.20',
        'GBP',
        'legacy',
        '',
        '',
        '',
        '',
        '',
        '',
        'G00 - Gross value of payment',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        'SFI12345678',
        '',
        'END'
      ],
      [
        'Ledger',
        'SOS275',
        '',
        'DRD10',
        '80003',
        2022,
        'RP00',
        'SFI12345678',
        '-0.10',
        'GBP',
        'legacy',
        '',
        '',
        '',
        '',
        '',
        '',
        'P02 - Over declaration penalty',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        'SFI12345678',
        '',
        'END'
      ]
    ])
  })
})
